# Generated by Django 3.1.3 on 2020-11-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modified',
            field=models.BooleanField(default=False),
        ),
    ]
